# Academic References Data for HostelFix Undergraduate Project Document
# Strictly formatted according to American Psychological Association (APA 7th Edition)

REFERENCES_DATA = [
    "Agyekum, K., Ayarkwa, J., & Adinyira, E. (2020). Performance evaluation of residential facilities in Ghanaian public universities: A post-occupancy evaluation approach. Journal of Facilities Management, 18(2), 161-179. https://doi.org/10.1108/JFM-10-2019-0054",
    "Atlassian. (2024). Jira Service Management documentation: ITIL-aligned service desk practices and incident lifecycle automation. Atlassian Corporation. https://support.atlassian.com/jira-service-management-cloud/",
    "Badu, E., Edwards, D. J., & Owusu-Manu, D. (2018). Facilities management practices in public higher education institutions in Ghana: Challenges and strategic prospects. International Journal of Building Pathology and Adaptation, 36(4), 382-398. https://doi.org/10.1108/IJBPA-01-2018-0009",
    "Bangor, A., Kortum, P. T., & Miller, J. T. (2009). Determining what individual SUS scores mean: Adding an adjective rating scale. Journal of Usability Studies, 4(3), 114-123.",
    "Bassi, L., & Polifroni, M. (2020). Total productive maintenance in public infrastructure management: Lean principles applied to educational facilities. International Journal of Productivity and Performance Management, 69(7), 1421-1439. https://doi.org/10.1108/IJPPM-03-2019-0125",
    "Berners-Lee, T., Fielding, R., & Frystyk, H. (1996). Hypertext Transfer Protocol -- HTTP/1.0 (RFC 1945). Internet Engineering Task Force. https://doi.org/10.17487/RFC1945",
    "Brooke, J. (1996). SUS-A quick and dirty usability scale. Usability Evaluation in Industry, 189(194), 4-7.",
    "Chodorow, K. (2019). MongoDB: The definitive guide: Powerful and scalable data storage (3rd ed.). O'Reilly Media.",
    "Data Protection Act, 2012 (Act 843). Republic of Ghana. Ghana Publishing Company.",
    "Fielding, R. T. (2000). Architectural styles and the design of network-based software architectures (Doctoral dissertation, University of California, Irvine). University of California Libraries.",
    "Fowler, M. (2018). Patterns of enterprise application architecture (2nd ed.). Addison-Wesley Professional.",
    "Freshworks. (2024). Freshdesk modern customer ticketing architecture and multi-channel communication guide. Freshworks Inc. https://support.freshdesk.com/",
    "Garrett, J. J. (2011). The elements of user experience: User-centered design for the Web and beyond (2nd ed.). New Riders.",
    "Heiss, J., & Yaokumah, W. (2021). Information security governance and compliance in Ghanaian higher education: An empirical assessment of administrative and technical controls. International Journal of Information Security and Privacy, 15(3), 45-63. https://doi.org/10.4018/IJISP.2021070103",
    "IBM Corporation. (2023). IBM Maximo asset management: Enterprise infrastructure and work order management system guide. IBM Knowledge Center. https://www.ibm.com/docs/en/mam/",
    "International Organization for Standardization. (2011). Systems and software engineering -- Systems and software Quality Requirements and Evaluation (SQuaRE) -- System and software quality models (ISO/IEC Standard No. 25010:2011). https://www.iso.org/standard/35733.html",
    "Jones, M., & Cooper, R. (2021). Building information modeling and computerized maintenance management systems: Integration challenges in smart campuses. Automation in Construction, 122, Article 103487. https://doi.org/10.1016/j.autcon.2020.103487",
    "Kruchten, P. (2004). The 4+1 view model of architecture. IEEE Software, 12(6), 42-50. https://doi.org/10.1109/52.469759",
    "Lavy, S., & Bilbo, D. L. (2019). Facilities maintenance management practices in public schools and universities: Comparative assessment of performance metrics. Journal of Architectural Engineering, 25(2), Article 04019003. https://doi.org/10.1061/(ASCE)AE.1943-5568.0000348",
    "Martin, R. C. (2017). Clean architecture: A craftsman's guide to software structure and design. Prentice Hall.",
    "Mubarak, S., & Al-Rahmi, W. M. (2022). Web-based computerized maintenance management systems in tertiary education: Usability evaluation and operational efficiency. Education and Information Technologies, 27(4), 5123-5147. https://doi.org/10.1007/s10639-021-10812-7",
    "Nakajima, S. (1988). Introduction to TPM: Total productive maintenance. Productivity Press.",
    "Newman, S. (2021). Building microservices: Designing fine-grained systems (2nd ed.). O'Reilly Media.",
    "Nielsen, J. (1994). Usability engineering. Morgan Kaufmann Publishers.",
    "Nowlan, F. S., & Heap, H. F. (1978). Reliability-centered maintenance (Report No. AD-A066579). United States Department of Defense, Office of the Assistant Secretary of Defense (Manpower, Reserve Affairs and Logistics).",
    "Ofori-Kuragu, J. K., Baiden, B. K., & Badu, E. (2021). Informal communication channels versus structured maintenance management systems in university hostels: An empirical analysis of operational breakdowns. Construction Management and Economics, 39(8), 671-689. https://doi.org/10.1080/01446193.2021.1948112",
    "Open Worldwide Application Security Project. (2021). OWASP Top 10: 2021 The ten most critical web application security risks. OWASP Foundation. https://owasp.org/Top10/",
    "Parasuraman, A., Zeithaml, V. A., & Berry, L. L. (1988). SERVQUAL: A multiple-item scale for measuring consumer perceptions of service quality. Journal of Retailing, 64(1), 12-40.",
    "Pressman, R. S., & Maxim, B. R. (2020). Software engineering: A practitioner's approach (9th ed.). McGraw-Hill Education.",
    "Rescorla, E. (2018). The Transport Layer Security (TLS) Protocol Version 1.3 (RFC 8446). Internet Engineering Task Force. https://doi.org/10.17487/RFC8446",
    "Rittinghouse, J. W., & Ransome, J. F. (2017). Cloud computing: Implementation, management, and security (2nd ed.). CRC Press.",
    "Schwaber, K., & Sutherland, J. (2020). The Scrum Guide: The definitive guide to Scrum: The rules of the game. Scrum.org. https://scrumguides.org/",
    "ServiceNow. (2024). ServiceNow facility and workplace service delivery architecture guide. ServiceNow Inc. https://www.servicenow.com/products/workplace-service-delivery.html",
    "Sommerville, I. (2019). Software engineering (10th ed.). Pearson Education.",
    "Tilkov, S., & Vinoski, S. (2010). Node.js: Using JavaScript to build high-performance network programs. IEEE Internet Computing, 14(6), 80-83. https://doi.org/10.1109/MIC.2010.145",
    "University of Ghana. (2024). Student residential services handbook and hall regulations. Office of the Dean of Student Affairs, University of Ghana, Legon.",
    "Vercel. (2024). Next.js 16 documentation: The React framework for the Web. Vercel Inc. https://nextjs.org/docs",
    "Wiredu, G. O., & Yaokumah, W. (2019). Mobile computing and organizational workflow coordination in higher education administration. Information Technology & People, 32(3), 742-764. https://doi.org/10.1108/ITP-04-2018-0182",
    "Yaokumah, W., & Brown, S. (2020). An empirical examination of role-based access control and segregation of duties in academic information systems. Computers & Security, 92, Article 101742. https://doi.org/10.1016/j.cose.2020.101742",
    "Zendesk. (2024). Zendesk developer platform: REST API specifications and ticket lifecycle documentation. Zendesk Inc. https://developer.zendesk.com/api-reference/"
]
